[package]
name = "testigo_macro"
version.workspace = true
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.37"
syn = { version = "2.0.77", features = ["full"] }
testigo_types = { path = "../testigo_types" }
inventory = { workspace = true }

